deepspeed train.py \
  --deepspeed ds_config.json \
  --model_name_or_path EleutherAI/gpt-neo-125M \
  --dataset_name Anthropic/hh-rlhf \
  --do_train 1 \
  --do_eval 1 \
  --report_to all \
  --max_seq_length 1024 \
  --per_device_train_batch_size 1 \
  --learning_rate 5e-5 \
  --num_train_epochs 1 \
  --output_dir output \
  --overwrite_output_dir \
  --logging_steps 100 \
  --save_steps 100 \
  --seed 42 \
  --bf16 1
